insert into users
  ("username", "email", "hashedPassword")
  values
    ('user1', 'user1@email.com', 'pw1');

insert into games
  ("userID", "gameName")
  values
    ('1', 'Code Words Vocab'),
    ('1', 'Tolkien Characters'),
    ('1', 'Pokemon Starters');

insert into lists
  ("userID", "listName")
  values
    ('1', 'HTML'),
    ('1', 'CSS'),
    ('1', 'JavaScript'),
    ('1', '(Tolkien) Hobbits'),
    ('1', '(Tolkien) Elves'),
    ('1', '(Tolkien) Dwarves'),
    ('1', '(Tolkien) Humans'),
    ('1', '(Tolkien) Istari'),
    ('1', '(Pokemon Starters) 1stGen'),
    ('1', '(Pokemon Starters) 2ndGen'),
    ('1', '(Pokemon Starters) 3rdGen');


insert into gamelist
  ("gameID", "listID")
  values
    ('1', '1'),
    ('1', '2'),
    ('2', '4'),
    ('2', '5'),
    ('2', '8'),
    ('3', '9');


insert into listwords
  ("listID", "word")
  values
    ('1', 'input'),
    ('1', 'label'),
    ('1', 'select'),
    ('1', 'textarea'),
    ('1', 'fieldset'),
    ('1', 'button'),
    ('1', 'dataset'),
    ('1', 'body'),
    ('1', 'head'),
    ('1', 'inline'),
    ('1', 'block'),
    ('2', 'selector'),
    ('2', 'ruleset'),
    ('2', 'class'),
    ('2', 'attribute'),
    ('2', 'flexbox'),
    ('2', 'nowrap'),
    ('2', 'display'),
    ('2', 'element'),
    ('2', 'margin'),
    ('2', 'padding'),
    ('2', 'border'),
    ('2', 'content'),
    ('2', 'inheritance'),
    ('2', 'transition'),
    ('3', 'variable'),
    ('3', 'assignment'),
    ('3', 'string'),
    ('3', 'number'),
    ('3', 'boolean'),
    ('3', 'undefined'),
    ('3', 'null'),
    ('3', 'symbol'),
    ('3', 'bigint'),
    ('3', 'function'),
    ('3', 'method'),
    ('3', 'object'),
    ('3', 'array'),
    ('3', 'callback'),
    ('3', 'promise'),
    ('3', 'initialize'),
    ('4', 'Bilbo'),
    ('4', 'Frodo'),
    ('4', 'Samwise'),
    ('4', 'Merry'),
    ('4', 'Pippin'),
    ('5', 'Legolas'),
    ('5', 'Elrond'),
    ('5', 'Galadriel'),
    ('5', 'Arwen'),
    ('6', 'Gimli'),
    ('6', 'Thoren'),
    ('6', 'Fili'),
    ('6', 'Kili'),
    ('6', 'Dwalin'),
    ('6', 'Balin'),
    ('6', 'Oin'),
    ('6', 'Gloin'),
    ('6', 'Dori'),
    ('6', 'Nori'),
    ('6', 'Bifur'),
    ('6', 'Bofur'),
    ('6', 'Bombur'),
    ('7', 'Aragorn'),
    ('7', 'Eowyn'),
    ('7', 'Theoden'),
    ('7', 'Boromir'),
    ('7', 'Faramir'),
    ('8', 'Sarumon'),
    ('8', 'Gandalf'),
    ('8', 'Radagast'),
    ('8', 'Alatar'),
    ('8', 'Pallando'),
    ('9', 'Bublasaur'),
    ('9', 'Ivysaur'),
    ('9', 'Venusaur'),
    ('9', 'Charmander'),
    ('9', 'Charmeleon'),
    ('9', 'Charizard'),
    ('9', 'Squirtle'),
    ('9', 'Wartortle'),
    ('9', 'Blastoise'),
    ('10', 'Chikorita'),
    ('10', 'Bayleef'),
    ('10', 'Meganium'),
    ('10', 'Cyndaquil'),
    ('10', 'Quilava'),
    ('10', 'Typhlosion'),
    ('10', 'Totodile'),
    ('10', 'Croconaw'),
    ('10', 'Feraligatr'),
    ('11', 'Treecko'),
    ('11', 'Grovyle'),
    ('11', 'Sceptile'),
    ('11', 'Torchic'),
    ('11', 'Combusken'),
    ('11', 'Blaziken'),
    ('11', 'Mudkip'),
    ('11', 'Marshtomp'),
    ('11', 'Swampert');
